ALTER TABLE harvest_waybills
    ALTER COLUMN crop_id DROP NOT NULL,
    ALTER COLUMN gross_weight_kg DROP NOT NULL,
    ALTER COLUMN tare_weight_kg DROP NOT NULL,
    ALTER COLUMN destination DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS document_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS shift_number VARCHAR(20),
    ADD COLUMN IF NOT EXISTS action_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS seed_type VARCHAR(100),
    ADD COLUMN IF NOT EXISTS mechanizator_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS trailer_number VARCHAR(30),
    ADD COLUMN IF NOT EXISTS tractor_model VARCHAR(100),
    ADD COLUMN IF NOT EXISTS equipment_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS departure_time TIME,
    ADD COLUMN IF NOT EXISTS return_time TIME,
    ADD COLUMN IF NOT EXISTS work_volume_ha NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS route_distance_km NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS start_odometer_km NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS end_odometer_km NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS start_engine_hours NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS end_engine_hours NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS fuel_issued_liters NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS fuel_start_liters NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS fuel_end_liters NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS fuel_actual_liters NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS receiver_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS weather_conditions VARCHAR(150),
    ADD COLUMN IF NOT EXISTS route_description TEXT,
    ADD COLUMN IF NOT EXISTS responsible_person VARCHAR(150),
    ADD COLUMN IF NOT EXISTS notes TEXT;
